#include "sortpicker.h"
#include "text.h"

#define NUM_SORTS (sizeof(sort_text) / sizeof(const char *))

static const char *const sort_text[] = {
	"\xa0\xa0 Selection Sort            1\n"
	"\xb0\xb0\n"
	"\n"
	"Repeatedly performs a linear\n"
	"search on the unsorted part of\n"
	"the array to find the smallest\n"
	"element, then swaps it with\n"
	"the element just after the\n"
	"sorted part.\n"
	"\n"
	"Makes up to 2n swaps and uses\n"
	"0.5n(n - 1) comparisons.\n"
	"\n"
	"Time:   O(n\x82)\n"
	"Space:  O(1)\n"
	"Stable: no\n"
	"\n"
	"Can be trivially improved by\n"
	"using double selection sort,\n"
	"which finds both the smallest\n"
	"and largest element on each\n"
	"pass, yielding a 33% reduction\n"
	"in comparisons.\n",

	"\xa0\xa0 Heap Sort                 2\n"
	"\xb0\xb0\n"
	"\n"
	"An improvement on selection\n"
	"sort which first organizes the\n"
	"data into a binary max heap\n"
	"and uses it to find the next\n"
	"largest element in O(logn)\n"
	"time. This is done by swapping\n"
	"the root node (index 0) with\n"
	"the bottom-right-most leaf,\n"
	"removing it from further\n"
	"consideration, and reordering\n"
	"to satisfy the heap property.\n"
	"\n"
	"The heap is stored implicitly\n"
	"on the original array. For any\n"
	"parent (index i), its left\n"
	"child is at 2i + 1 and its\n"
	"right child is at 2i + 2.\n"
	"\n"
	"Time:   O(nlogn)\n"
	"Space:  O(1)\n"
	"Stable: no\n",

	"\xa0\xa0 Insertion Sort            3\n"
	"\xb0\xb0\n"
	"\n"
	"For each element in the array,\n"
	"uses a linear search to find\n"
	"its position in the already\n"
	"sorted part and then does a\n"
	"series of swaps to insert it.\n"
	"\n"
	"Insertion sort has low\n"
	"constant factors with respect\n"
	"to the basic O(n\x82)\n"
	"algorithms, so it sees regular\n"
	"use in more sophisticated\n"
	"algorithms.\n"
	"\n"
	"Using a binary search yields\n"
	"O(nlogn) comparisons, but does\n"
	"not affect writes.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     yes\n",

	"\xa0\xa0 Shell Sort                4\n"
	"\xb0\xb0\n"
	"\n"
	"Uses multiple gapped insertion\n"
	"sort passes with decreasing\n"
	"gap sizes to move items long\n"
	"distances quickly.\n"
	"\n"
	"The time complexity depends on\n"
	"the gap sequence used. This\n"
	"implementation uses Ciura's\n"
	"gap sequence: 1, 4, 10, 23,\n"
	"57... As this gap sequence is\n"
	"empirically derived, precise\n"
	"details on its time complexity\n"
	"are unknown, but its average\n"
	"performance is the best\n"
	"currently known.\n"
	"\n"
	"Best:    O(nlogn)\n"
	"Average: O(~n\x85\x8e\x84)\n"
	"Worst:   Unknown\n"
	"Space:   O(1)\n"
	"Stable:  no\n",

	"\xa0\xa0 Bubble Sort               5\n"
	"\xb0\xb0\n"
	"\n"
	"Repeatedly passes through the\n"
	"array left to right, swapping\n"
	"adjacent items if out of\n"
	"order. Passes are made until\n"
	"no swaps are performed. The\n"
	"effect of each pass is that\n"
	"the largest element is moved\n"
	"to the end.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     yes\n",

	"\xa0\xa0 Comb Sort                 6\n"
	"\xb0\xb0\n"
	"\n"
	"Repeatedly performs gapped\n"
	"bubble sort passes with\n"
	"decreasing gaps until the\n"
	"array is sorted. There are\n"
	"more passes than in Shell sort\n"
	"and the final pass may need to\n"
	"be repeated several times, so\n"
	"it is still O(n\x82) on average;\n"
	"however, it is competitive\n"
	"with O(nlogn) sorts for most\n"
	"practically sized data.\n"
	"\n"
	"The shrink factor used in\n"
	"this implementation is 1.3.\n"
	"\n"
	"Best:       O(nlogn)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     no\n",

	"\xa0\xa0 Gnome Sort                7\n"
	"\xb0\xb0\n"
	"\n"
	"A simplified variant of\n"
	"insertion sort which operates\n"
	"step-wise on pairs of items.\n"
	"If out of order, the gnome\n"
	"swaps them and moves left. If\n"
	"they are in order or the\n"
	"beginning of the array is\n"
	"reached, the gnome moves\n"
	"right. Once the gnome leaves\n"
	"the end of the array, the sort\n"
	"is completed.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     yes\n",

	"\xa0\xa0 Cocktail Shaker Sort      8\n"
	"\xb0\xb0\n"
	"\n"
	"Same as bubble sort, but the\n"
	"step direction is reversed on\n"
	"each pass, yielding a small\n"
	"performance improvement.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     yes\n",

	"\xa0\xa0 Quick Sort (LR pointers)  9\n"
	"\xb0\xb0\n"
	"\n"
	"Selects a pivot, moves all\n"
	"elements smaller than it to\n"
	"the left of it and all larger\n"
	"elements to the right, then\n"
	"recursively does the same with\n"
	"both resulting partitions.\n"
	"\n"
	"Deterministic pivot selection\n"
	"(first, middle, median of\n"
	"medians) can lead to quadratic\n"
	"performance when the resulting\n"
	"partitions are too lopsided as\n"
	"a result of adversarial input.\n"
	"\n"
	"Best/Avg.: O(nlogn)\n"
	"Worst:     O(n\x82)\n"
	"Space:     O(n) stack (naive)\n"
	"           O(log n) stack\n"
	"Stable:    no\n",

	"\xa0\xa0 Merge Sort               10\n"
	"\xb0\xb0\n"
	"\n"
	"Sorts the array into\n"
	"increasingly large ascending\n"
	"runs by merging pairs of runs\n"
	"using an auxiliary buffer.\n"
	"Runs of size 1 are considered\n"
	"to be already sorted.\n"
	"\n"
	"This can be, and often is done\n"
	"iteratively, but as the\n"
	"recursive version is more\n"
	"well-known and easier to\n"
	"implement, it is used here.\n"
	"This does not affect the time\n"
	"or overall space complexity.\n"
	"\n"
	"Time:   O(nlogn)\n"
	"Space:  O(n) (+ O(logn) stack)\n"
	"Stable: yes\n",

	"\xa0\xa0 Introspective Sort       11\n"
	"\xb0\xb0\n"
	"\n"
	"Uses quick sort until the\n"
	"resulting partitions are of a\n"
	"trivial size, and completes\n"
	"the sort with a final\n"
	"insertion sort pass, taking\n"
	"advantage of its low overhead.\n"
	"\n"
	"The pivot selection used is\n"
	"vulnerable to adversarial\n"
	"input, so heap sort is used\n"
	"when the recursion depth\n"
	"exceeds a certain number to\n"
	"guarantee O(nlogn) runtime.\n"
	"\n"
	"Time:   O(nlogn)\n"
	"Space:  O(logn) stack\n"
	"Stable: no\n",

	"\xa0\xa0 Tim Sort                 12\n"
	"\xb0\xb0\n"
	"\n"
	"A hybrid merge sort designed\n"
	"by Tim Peters which takes\n"
	"advantage of existing order in\n"
	"the data (i.e. is adaptive).\n"
	"It uses insertion sort to\n"
	"extend runs up to a minimum\n"
	"size.\n"
	"\n"
	"Owing to its superior space\n"
	"usage over traditional merge\n"
	"sort (just over half) and its\n"
	"nearly linear runtime in a\n"
	"great deal of cases, it is\n"
	"a common production algorithm.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(nlogn)\n"
	"Space:      O(n)\n"
	"Stable:     no\n",

	"\xa0\xa0 Counting Sort            13\n"
	"\xa0\xa0 (distributive sort)\n"
	"\n"
	"Counts the occurrences of each\n"
	"key in the array, calculates a\n"
	"prefix sum, and moves through\n"
	"the original array in reverse\n"
	"order to copy the keys stably\n"
	"to an auxiliary array.\n"
	"\n"
	"Being a distributive sort\n"
	"(as opposed to a comparison\n"
	"sort) it requires keys which\n"
	"are integers or integer-like.\n"
	"\n"
	"Where k is the range of keys:\n"
	"\n"
	"Time:   O(n + k)\n"
	"Space:  O(n + k)\n"
	"Stable: no\n",

	"\xa0\xa0 Base 4 LSD Radix Sort    14\n"
	"\xa0\xa0 (distributive sort)\n"
	"\n"
	"Distributes items into buckets\n"
	"lexicographically based on\n"
	"their digits instead of using\n"
	"comparisons. Where d is the\n"
	"number of digits and k is the\n"
	"range of possible digits:\n"
	"\n"
	"Time:   O(d(n + k))\n"
	"Space:  O(n + k)\n"
	"Stable: no\n"
	"\n"
	"Radix sort uses counting sort\n"
	"internally to stably sort by\n"
	"each digit.\n",

	"\xa0\xa0 Base 4 MSD Radix Sort    15\n"
	"\xa0\xa0 (distributive sort)\n"
	"\n"
	"Same as LSD Radix Sort, using\n"
	"the most significant digit\n"
	"instead. Since this provides\n"
	"the opportunity for early-exit\n"
	"optimizations, the MSD\n"
	"variation has a better best\n"
	"case time complexity.\n"
	"\n"
	"Best:       O(n)\n"
	"Avg./Worst: O(d(n + k))\n"
	"Space:      O(n + k)\n"
	"Stable:     sometimes\n"
	"\n"
	"Radix sort uses counting sort\n"
	"internally to stably sort by\n"
	"each digit.\n",

	"\xa0\xa0 Cycle Sort               16\n"
	"\xb0\xb0\n"
	"\n"
	"Uses the minimum possible\n"
	"number of writes to sort the\n"
	"array by factoring it into\n"
	"cycles. Each item is either\n"
	"written once to put it in its\n"
	"final spot, or left alone if\n"
	"it is already correct.\n"
	"\n"
	"Time:   O(n\x82)\n"
	"Space:  O(1)\n"
	"Stable: no\n",

	"\xa0\xa0 Circle Sort              17\n"
	"\xb0\xb0\n"
	"\n"
	"Compares and swaps each pair\n"
	"of diametrically opposed\n"
	"elements and divides the array\n"
	"into two even partitions,\n"
	"doing the same with each\n"
	"recursively. Since this\n"
	"results in only a partial\n"
	"sort, this is repeated until\n"
	"no swaps occur.\n"
	"\n"
	"In effect, this sort is\n"
	"similar to quick sort in the\n"
	"same way comb sort is to Shell\n"
	"sort. Unlike quick sort,\n"
	"circle sort may be done\n"
	"iteratively for O(1) space.\n"
	"\n"
	"Best:       O(nlogn)\n"
	"Avg./Worst: O(nlog\x82n)\n"
	"Space:      O(logn) stack\n"
	"Stable:     no\n",

	"\xa0\xa0 Pancake Sort             18\n"
	"\xb0\xb0\n"
	"\n"
	"A variation of selection sort\n"
	"which only moves elements by\n"
	"flipping a number of elements\n"
	"at the top of a stack (i.e\n"
	"using reversals) where the\n"
	"\"spatula\" can be inserted at\n"
	"any point. This results in\n"
	"many unnecessary writes.\n"
	"\n"
	"A recursive merge sort\n"
	"variation with O(nlog\x82n)\n"
	"runtime exists.\n"
	"\n"
	"Best:       O(n\x82)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(1)\n"
	"Stable:     no\n",

	"\xa0\xa0 Bitonic Merge Sort       19\n"
	"\xb0\xb0\n"
	"\n"
	"A sorting network designed to\n"
	"run in O(log\x82n) parallel\n"
	"time. It creates bitonic\n"
	"sequences by sorting the\n"
	"second of two parts in\n"
	"decreasing order and merging\n"
	"them with a bitonic merge.\n"
	"\n"
	"Since merging itself requires\n"
	"O(logn) passes of O(n) time to\n"
	"complete, merging is O(nlogn),\n"
	"which combined with O(logn)\n"
	"merge steps makes the overall\n"
	"runtime asymptotically\n"
	"suboptimal when run\n"
	"sequentially.\n"
	"\n"
	"Time:   O(nlog\x82n)\n"
	"Space:  O(1)\n"
	"        parallel O(log\x82n)\n"
	"Stable: no\n",

	"\xa0\xa0 Ford-Johnson Algorithm   20\n"
	"\xa0\xa0 \"Merge-Insertion\" Sort\n"
	"\n"
	"Groups elements into pairs of\n"
	"\"winners\" and \"losers\", then\n"
	"recursively sorts the winners\n"
	"while maintaining pairs.\n"
	"Binary insertion, done in an\n"
	"unusual order, is used to\n"
	"combine them.\n"
	"\n"
	"Because relative order can be\n"
	"deduced by carefully managing\n"
	"the original pairs, this sort\n"
	"(although not optimal) uses\n"
	"close to the lower bound of\n"
	"required comparisons,\n"
	"log\x92n! ~ nlog\x92n - 1.443n.\n"
	"\n"
	"Best:       O(nlogn)\n"
	"Avg./Worst: O(n\x82)\n"
	"Space:      O(logn) stack\n"
	"Stable:     no\n",

	"\xa0\xa0 Block Merge Sort         21\n"
	"\xb0\xb0\n"
	"\n"
	"The first practical stable\n"
	"and asymptotically optimal\n"
	"sort with O(1) extra memory.\n"
	"It takes the form of an\n"
	"iterative merge sort which\n"
	"uses rotations to divide\n"
	"merges into blocks and\n"
	"performs smaller local merges\n"
	"on them.\n"
	"\n"
	"Despite its advantages, block\n"
	"merge sort is now largely of\n"
	"theoretical interest due to\n"
	"its relatively high constant\n"
	"factors and extreme complexity\n"
	"and implementation cost.\n"
	"\n"
	"Time:   O(nlogn)\n"
	"Space:  O(1)\n"
	"Stable: yes\n",

	"\xa0\xa0 Stooge Sort              22\n"
	"\xb0\xb0\n"
	"\n"
	"Recursively sorts the first\n"
	"2/3 of the array, the last\n"
	"2/3, and then the first 2/3\n"
	"again. On each partition, the\n"
	"first and last elements are\n"
	"swapped if out of order. This\n"
	"results in an abysmal\n"
	"superquadratic runtime.\n"
	"\n"
	"Time:   O(n\x8f\x90\x91\x83\x8e\x8f\x90\x91\x81\x8a\x85)\n"
	"        O(~n\x82\x8a\x87\x80\x89\x85\x8a\x8a\x8a)\n"
	"Space:  O(logn) stack\n"
	"Stable: no\n",

	"\xa0\xa0 Slow Sort                23\n"
	"\xb0\xb0\n"
	"\n"
	"An impractical merge-sort-like\n"
	"algorithm which deliberately\n"
	"recurses over as much of the\n"
	"array as possible. Does not\n"
	"complete in polynomial time.\n"
	"\n"
	"Even for relatively small\n"
	"array sizes, the runtime\n"
	"is absurd.\n"
	"\n"
	"Time:   o(n\x80\x8a\x85\x8f\x90\x91\x8d)\n"
	"Space:  O(n) stack\n"
	"Stable: no\n"
	"\n"
	"This implementation uses an\n"
	"O(logn) stack optimization as\n"
	"it would otherwise cause a\n"
	"stack overflow. This is done\n"
	"by just factoring the tail\n"
	"recursion into a loop.\n",

	"\xa0\xa0 Bogo Sort                24\n"
	"\xb0\xb0\n"
	"\n"
	"A non-deterministic algorithm\n"
	"which repeatedly shuffles the\n"
	"list until it is in order.\n"
	"With any non-trivial value of\n"
	"n, this sort is not expected\n"
	"to complete.\n"
	"\n"
	"Best:    O(n)\n"
	"Average: O(n x n!)\n"
	"Worst:   Unbounded\n"
	"Space:   O(1)\n"
	"Stable:  Probably not\n"
	"\n"
	"Probability of the sort\n"
	"preserving the initial order\n"
	"of duplicates is the product\n"
	"of 1/k! for each distinct item\n"
	"where k is the number of\n"
	"instances.\n"
};

static uint8_t cur_index; // initialized to 0 on startup

static void init(void) {
	text_init(sort_text[cur_index]);
}

SortFunction sortpicker_run(void) {
	static uint8_t buttons;

	init();

	while (1) {
		(void)nes_get_rand8();
		buttons = nes_get_new_buttons();

		if (buttons & NES_BUTTON_START)
			return (SortFunction)0;

		if (buttons & NES_BUTTON_RIGHT) {
			++cur_index;
			if (cur_index >= NUM_SORTS)
				cur_index = 0;
			text_init(sort_text[cur_index]);
		} else if (buttons & NES_BUTTON_LEFT) {
			--cur_index;
			if (cur_index >= NUM_SORTS)
				cur_index = NUM_SORTS - 1;
			text_init(sort_text[cur_index]);
		} else if (buttons & NES_BUTTON_UP) {
			cur_index += 5;
			if (cur_index >= NUM_SORTS)
				cur_index = NUM_SORTS - 1;
			text_init(sort_text[cur_index]);
		} else if (buttons & NES_BUTTON_DOWN) {
			cur_index -= 5;
			if (cur_index >= NUM_SORTS)
				cur_index = 0;
			text_init(sort_text[cur_index]);
		}
		
		text_update();
		nes_hide_spr(0);
		nes_wait_frame();
	}
}
